name: Docker Image CI Handler For FullStackOpen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Part 04 Blog-Backend
      run: docker build . --file Dockerfile --tag fullstack-blog-back:pt-04
      working-directory: ./part4/blog-backend


