name: Docker Image CI Handler For FullStackOpen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Part 04 Blog-Backend
      id: docker_build
      run: docker build . --file Dockerfile --tag fullstack-blog-back:pt-04
      working-directory: part4/blog

    - name: Login to DockerHub
      id: docker_login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image to DockerHub
      if: steps.docker_build.outcome == 'success' && steps.docker_login.outcome == 'success'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./part4/blog/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fullstack-blog-back:pt-04
      



