name: Docker Image CI Handler For FullStackOpen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Part 04 Blog-Backend
      id: docker_build
      run: docker build . --file Dockerfile --tag fullstack-blog-back:pt-04
      working-directory: part4/blog

    - name: Deploy to Docker Hub
      if: steps.docker_build.outcome == 'success'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fullstack-blog-back:pt-04
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./Dockerfile
        workdir: part4/blog



